name: Export PDFs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Merge into exports
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: exports
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          ref: exports
      - name: Install MuseScore
        run: |
          sudo apt install flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y --noninteractive flathub org.musescore.MuseScore
      - name: Export charts to PDFs
        uses: coactions/setup-xvfb@v1
        with:
          working-directory: ./
          run: bash export-charts.sh
      - name: Tidy
        run: |
          rm -rf chart-exports
          mv temp-exports chart-exports
      - name: Make zip of charts
        uses: vimtor/action-zip@v1
        with:
          files: chart-exports/
          dest: chart-exports.zip
      - name: Export lyrics to PDFs
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: raw-lyrics
          output_dir: lyrics-exports
          # build_html: false
      - name: Commit and push
        run: |
          git config --global user.email "me@chrishampson.co.uk"
          git config --global user.name "MuseScore Export Bot"
          git add .
          git commit -am "Updating exports"
          git push
